#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Unstructured Minds — Interactive Setup
# =============================================================================
# Creates a .env file from your answers. Run: ./setup.sh or make setup

BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m'

ENV_FILE=".env"

echo ""
echo -e "${BOLD}Unstructured Minds — Setup${NC}"
echo -e "${DIM}This will create your .env file.${NC}"
echo ""

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}A .env file already exists.${NC}"
    read -p "Overwrite it? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Done."
        exit 0
    fi
    echo ""
fi

# ---- LLM Provider ----
echo -e "${BOLD}1. AI / LLM Provider${NC}"
echo -e "${DIM}   Powers data extraction and natural language queries.${NC}"
echo -e "${DIM}   The app works without it — AI features are just disabled.${NC}"
echo ""
echo "   Providers: anthropic, openai, ollama (local, free), or skip"
read -p "   Provider [skip]: " llm_provider
llm_provider="${llm_provider:-skip}"

llm_api_key=""
llm_model_fast=""
llm_model_smart=""

if [ "$llm_provider" != "skip" ]; then
    if [ "$llm_provider" != "ollama" ]; then
        read -p "   API key: " llm_api_key
    fi
    read -p "   Fast model override (enter to use default): " llm_model_fast
    read -p "   Smart model override (enter to use default): " llm_model_smart
fi
echo ""

# ---- Storage ----
echo -e "${BOLD}2. Storage Mode${NC}"
echo -e "${DIM}   local  = DuckDB file, zero setup (default)${NC}"
echo -e "${DIM}   postgres = Postgres database${NC}"
echo ""
read -p "   Storage mode [local]: " storage_mode
storage_mode="${storage_mode:-local}"

database_url=""
if [ "$storage_mode" = "postgres" ]; then
    echo ""
    echo -e "${DIM}   Use 'bundled' for the built-in Docker Postgres, or paste a URL.${NC}"
    read -p "   DATABASE_URL [bundled]: " database_url
    if [ "$database_url" = "bundled" ] || [ -z "$database_url" ]; then
        database_url="postgresql://um:um_dev_password@postgres:5432/unstructured_minds"
    fi
fi
echo ""

# ---- Auth ----
echo -e "${BOLD}3. Authentication${NC}"
echo -e "${DIM}   none  = No auth (default, good for local use)${NC}"
echo -e "${DIM}   basic = Username/password${NC}"
echo -e "${DIM}   clerk = Clerk.com (multi-user)${NC}"
echo ""
read -p "   Auth mode [none]: " auth_mode
auth_mode="${auth_mode:-none}"

basic_user=""
basic_pass=""
clerk_secret=""
clerk_domain=""
clerk_pub_key=""

if [ "$auth_mode" = "basic" ]; then
    read -p "   Username [admin]: " basic_user
    basic_user="${basic_user:-admin}"
    read -sp "   Password: " basic_pass
    echo ""
elif [ "$auth_mode" = "clerk" ]; then
    read -p "   CLERK_SECRET_KEY: " clerk_secret
    read -p "   CLERK_DOMAIN: " clerk_domain
    read -p "   VITE_CLERK_PUBLISHABLE_KEY: " clerk_pub_key
fi
echo ""

# ---- Write .env ----
cat > "$ENV_FILE" << ENVFILE
# =============================================================================
# Unstructured Minds — Generated by setup.sh
# =============================================================================

# AI / LLM
ENVFILE

if [ "$llm_provider" != "skip" ]; then
    echo "LLM_PROVIDER=$llm_provider" >> "$ENV_FILE"
    [ -n "$llm_api_key" ] && echo "LLM_API_KEY=$llm_api_key" >> "$ENV_FILE"
    [ -n "$llm_model_fast" ] && echo "LLM_MODEL_FAST=$llm_model_fast" >> "$ENV_FILE"
    [ -n "$llm_model_smart" ] && echo "LLM_MODEL_SMART=$llm_model_smart" >> "$ENV_FILE"
else
    echo "# LLM_PROVIDER=anthropic" >> "$ENV_FILE"
    echo "# LLM_API_KEY=" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << ENVFILE

# Storage
STORAGE_MODE=$storage_mode
ENVFILE

[ -n "$database_url" ] && echo "DATABASE_URL=$database_url" >> "$ENV_FILE"

cat >> "$ENV_FILE" << ENVFILE

# Auth
AUTH_MODE=$auth_mode
ENVFILE

if [ "$auth_mode" = "basic" ]; then
    echo "BASIC_AUTH_USERNAME=$basic_user" >> "$ENV_FILE"
    echo "BASIC_AUTH_PASSWORD=$basic_pass" >> "$ENV_FILE"
elif [ "$auth_mode" = "clerk" ]; then
    echo "CLERK_SECRET_KEY=$clerk_secret" >> "$ENV_FILE"
    echo "CLERK_DOMAIN=$clerk_domain" >> "$ENV_FILE"
    echo "VITE_CLERK_PUBLISHABLE_KEY=$clerk_pub_key" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << ENVFILE

# Paths
VAULT_PATH=./vault
DATA_PATH=./data

# Server
HOST=0.0.0.0
PORT=8000
FRONTEND_PORT=3000
DEBUG=false
ENVFILE

echo ""
echo -e "${GREEN}Created .env successfully.${NC}"
echo ""
echo -e "${BOLD}Next steps:${NC}"
if [ "$storage_mode" = "postgres" ] && [ "$database_url" = "postgresql://um:um_dev_password@postgres:5432/unstructured_minds" ]; then
    echo -e "  ${CYAN}make up-postgres${NC}     Start with bundled Postgres"
else
    echo -e "  ${CYAN}make up${NC}              Start in local mode"
fi
echo -e "  ${CYAN}make dev${NC}             Start in dev mode (hot reload)"
echo ""
